export const categories = {
  noCategory: {
    name: 'Not category',
    icon: '⬜️',
  },
  propsCategories: [
    {
      name: 'Text',
      icon: '🖌',
      props: [
        'font-family',
        'font-size',
        'font-weight',
        'list-style-type',
        'text-decoration',
        'line-height',
        'text-align',
        'text-transform',
        'white-space',
        'outline',
      ],
    },
    {
      name: 'Box model',
      icon: '📦',
      props: [
        'display',
        'flex-direction',
        'flex-wrap',
        'flex-flow',
        'flex',
        'flex-basis',
        'column-gap',
        'row-gap',
        'box-sizing',
        'align-items',
        'align-self',
        'justify-content',
        '-webkit-box-orient',
      ],
    },
    {
      name: 'Position',
      icon: '📍',
      props: ['position', 'top', 'right', 'bottom', 'left'],
    },
    {
      name: 'Visibility',
      icon: '👀',
      props: ['overflow', 'overflow-y', 'z-index', 'opacity'],
    },
    {
      name: 'Background',
      icon: '🖼',
      props: [
        'background-color',
        'background',
        'background-image',
        'background-repeat',
        'background-position-x',
        'background-position-y',
        'background-size',
      ],
    },
    {
      name: 'Color',
      icon: '🖍',
      props: ['color'],
    },
    {
      name: 'Manipulation',
      icon: '🔧',
      props: ['transform', 'transition-property', 'transition-timing-function', 'transition-duration'],
    },
    {
      name: 'FX',
      icon: '✨',
      props: [
        'cursor',
        'box-shadow',
        'border',
        'border-width',
        'border-top',
        'border-bottom',
        'border-left',
        'border-right',
        'border-bottom-right-radius',
        'border-bottom-left-radius',
        'border-bottom-color',
        'border-bottom-style',
        'border-bottom-width',
        'border-style',
        'border-color',
        'border-radius',
        'outline-color',
        'appearance',
        'pointer-events',
      ],
    },
    {
      name: 'Dimensions',
      icon: '📐',
      props: [
        'max-width',
        'min-width',
        'min-height',
        'height',
        'width',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
      ],
    },
  ],
}
